version: '3.7'

services:
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=module-db 
      - MYSQL_USER=module 
      - MYSQL_PASSWORD=module 
      - MYSQL_ROOT_PASSWORD=root
    volumes: 
      - ./dbdata:/var/lib/mysql
      - ./scripts:/docker-entrypoint-initdb.d
    networks:
      - database-network
  application:
    image: andersonfsilva/module-api:latest
    environment: 
      - DB_USERNAME=module
      - DB_PASSWORD=module
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=module-db
    entrypoint: dockerize -wait tcp://mysql:3306 -wait java -jar /app.jar
    networks:
      - database-network
      - proxy-network
    depends_on: 
      - mysql
  reverse-proxy:
    image: andersonfsilva/web-proxy:latest
    ports: 
      - 8000:80
    entrypoint: dockerize -wait http://application:3333 /docker-entrypoint.sh nginx -g daemon
    depends_on: 
      - application
    networks:
      - proxy-network
networks:
  database-network:
    driver: bridge
  proxy-network:
    driver: bridge
